name: Winnipeg API Client Test

on:
  push:
    branches: [ "main" ]
    paths: [ "transit-api-client/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "transit-api-client/**" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  WPG_TRANSIT_API_KEY: "${{ secrets.WPG_TRANSIT_API_KEY }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache build files
      id: cache-cargo
      uses: actions/cache@v3
      env:
        cache-name: cargo-cache
      with:
        path: |
          ~/.cargo
          ./transit-api-client/target
        key: ${{ runner.os }}-transit-test-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build
      run: cargo build --verbose
      working-directory: transit-api-client
      env:
        RUSTFLAGS: -D warnings

    # Needed, because function dotenv::dotenv() needs the file to exist, even if
    # environment variable is not set in file.
    - name: Prepare .env file
      run: touch .env
      working-directory: transit-api-client
      env:
        RUSTFLAGS: -D warnings

    - name: Run tests
      run: cargo test --verbose
      working-directory: transit-api-client
      env:
        RUSTFLAGS: -D warnings

    - name: Build documentation
      run: cargo dov --no-deps
      working-directory: transit-api-client
      env:
        RUSTFLAGS: -D warnings

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cargo fmt
      run: cargo fmt -- --check
      working-directory: transit-api-client

    - name: clippy
      run: cargo clippy --all-features --no-deps
      working-directory: transit-api-client
      env:
        RUSTFLAGS: -D warnings
