name: 'Publish Release Assets'

on:
  workflow_dispatch:

jobs:
  # Build and upload release artifacts
  build-tauri:
    name: "Build the application for different architectures"
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            arch: x86_64
            target: x86_64-apple-darwin
# Not working currently?
#          - buid: macos
#            os: macos-latest
#            arch: aarch64
#            target: aarch64-apple-darwin
          - build: windows
            os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseBody: 'CHANGE ME'
          releaseDraft: true
          prerelease: false
      
      - name: "Build documentation PDFs"
        if: matrix.os == 'ubuntu-latest'
        working-directory: "docs"
        run: |
          wget "https://github.com/typst/typst/releases/download/$(gh api 'https://api.github.com/repos/typst/typst/releases/latest' | jq -r '.tag_name')/typst-x86_64-unknown-linux-musl.tar.xz"
          tar xvf typst-x86_64-unknown-linux-musl.tar.xz
          ./typst-x86_64-unknown-linux-musl/typst compile introduction.typ
          ./typst-x86_64-unknown-linux-musl/typst compile conclusion.typ
          gh release upload "${{ steps.tauri.outputs.releaseId }}" ../LICENSE.md conclusion.pdf introduction.pdf
        env:
          GH_TOKEN: ${{ github.token }}
